### ISSUE TITLE
bounty test issue

### ISSUE THREAD

**Issue by jiangbubai** [jiangbubai/api-v1-client-java#1]
bounty test issue

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0xf73ff2df51d8eb00d4ea1785754c2e63d0d422dc](https://ropsten.etherscan.io/address/0xf73ff2df51d8eb00d4ea1785754c2e63d0d422dc)
![QR Code](https://openbounty.status.im:444/qr/jiangbubai/api-v1-client-java/bounty/1/cd60dd669caa0e6d873328d2511802aefb267b357a73dd1c5fcc05ffded2ce3b/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
