### ISSUE TITLE
test 

### ISSUE THREAD

**Issue by jiangbubai** [jiangbubai/api-v1-client-java#2]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x8c791e0170f579d36d855ccdc28aa3372dc6a0d9](https://ropsten.etherscan.io/address/0x8c791e0170f579d36d855ccdc28aa3372dc6a0d9)
![QR Code](https://openbounty.status.im:444/qr/jiangbubai/api-v1-client-java/bounty/2/a183571e8b02dc0ec43683b4efbdb79c67b9aabc1e816ae09fcde238ea60054d/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
