### ISSUE TITLE
Hi bounty

### ISSUE THREAD

**Issue by jiangbubai** [jiangbubai/api-v1-client-java#3]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x0ee83a591014e5e3dd4409e63fb5dcda2e687ce2](https://etherscan.io/address/0x0ee83a591014e5e3dd4409e63fb5dcda2e687ce2)
![QR Code](https://openbounty.status.im/qr/jiangbubai/api-v1-client-java/bounty/3/95dd386522e7ebb3d24f0da488a766fefc5bb5bb1e72669863f80ea29dc2c83d/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x3dba86dceb70a5e5a84e571796d1f4ebcbdd7829](https://ropsten.etherscan.io/address/0x3dba86dceb70a5e5a84e571796d1f4ebcbdd7829)
![QR Code](https://openbounty.status.im:444/qr/jiangbubai/api-v1-client-java/bounty/3/95dd386522e7ebb3d24f0da488a766fefc5bb5bb1e72669863f80ea29dc2c83d/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
