### ISSUE TITLE
fdsafd

### ISSUE THREAD

**Issue by jiangbubai** [jiangbubai/api-v1-client-java#4]
43

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0xfc59fffab09a88d3db06a72b631498592aa140ca](https://etherscan.io/address/0xfc59fffab09a88d3db06a72b631498592aa140ca)
![QR Code](https://openbounty.status.im/qr/jiangbubai/api-v1-client-java/bounty/4/72ee9d020e1b86fe71262590edc797bc237d3ec884b43f115264e7f84537f3b7/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0xb8d65d814d590e1c29b5eef220163f23b0acb059](https://ropsten.etherscan.io/address/0xb8d65d814d590e1c29b5eef220163f23b0acb059)
![QR Code](https://openbounty.status.im:444/qr/jiangbubai/api-v1-client-java/bounty/4/72ee9d020e1b86fe71262590edc797bc237d3ec884b43f115264e7f84537f3b7/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
