### ISSUE TITLE
try it again

### ISSUE THREAD

**Issue by jiangbubai** [jiangbubai/api-v1-client-java#5]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x8374d7068cb181579fc0a00be8c28724ce8bad0d](https://ropsten.etherscan.io/address/0x8374d7068cb181579fc0a00be8c28724ce8bad0d)
![QR Code](https://openbounty.status.im:444/qr/jiangbubai/api-v1-client-java/bounty/5/8dde3b49599f7dfe9812ba500993ca95ad382cbdf5e33780e82a2007f3fecc1d/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://openbounty.status.im:444](https://openbounty.status.im:444) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
