### ISSUE TITLE
WE need a logo

### ISSUE THREAD

**Issue by jiangbubai** [jiangbubai/api-v1-client-java#6]

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0xfde56df6a9bde68594ea616de1c93a1ccd5b641c](https://etherscan.io/address/0xfde56df6a9bde68594ea616de1c93a1ccd5b641c)
![QR Code](https://openbounty.status.im/qr/jiangbubai/api-v1-client-java/bounty/6/29edf20f32b6db707ddb0c4d13d0b630267554921759fcd086a4a9c900b63595/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
